create table if not exists jenkins_versions (
    id int generated by default as identity primary key,
    version varchar(32)
);

create unique index jenkins_version_version on jenkins_versions(version);

CREATE TABLE IF NOT EXISTS instance_reports (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    instance_id varchar(64) NOT NULL,
    report_time timestamptz NOT NULL,
    year smallint NOT NULL,
    month smallint NOT NULL,
    version int references jenkins_versions,
    servlet_container text,
    count_for_month int default 0
);

create index instance_reports_year_month on instance_reports using btree(year, month);
create index instance_reports_instance_id_year_month on instance_reports using btree(instance_id, year, month);

CREATE TABLE IF NOT EXISTS plugins (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL,
    version text NOT NULL
);

create unique index plugins_name_and_version on plugins using btree(name, version);
create index plugins_name on plugins(name);

create table if not exists plugin_reports (
    id int generated by default as identity primary key,
    report_id int references instance_reports,
    plugin_id int references plugins
);

create index plugin_reports_report_id on plugin_reports(report_id);
create index plugin_reports_plugin_id on plugin_reports(plugin_id);

CREATE TABLE IF NOT EXISTS job_types (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text NOT NULL
);

create unique index job_type_name on job_types(name);

create table if not exists job_reports (
    id int generated by default as identity primary key,
    report_id int references instance_reports,
    job_type_id int references job_types,
    count int default 0
);

create index job_report_report_id on job_reports(report_id);
create index job_report_type_id on job_reports(job_type_id);

CREATE TABLE IF NOT EXISTS os_types (
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     name text NOT NULL
);

create unique index os_type_name on os_types(name);

create table if not exists jvm_versions (
    id int generated by default as identity primary key,
    name text NOT NULL
);

create unique index jvm_version_name on jvm_versions(name);

create table if not exists nodes (
    id int generated by default as identity primary key,
    report_id int references instance_reports,
    os_id int references os_types,
    jvm_version_id int references jvm_versions,
    executors int default 0,
    jvm_name text,
    jvm_vendor text,
    is_controller boolean default false
);

create index node_report_id on nodes(report_id);
create index node_os_id on nodes(os_id);
